### ISSUE TITLE
Test Custom Errors without specifying the expected value for arguments

### ISSUE THREAD

**Issue by christophelebrun** [TomiOhl/custom-error-test-helper#2]
Is it possible to test for custom errors that have argument, but not to test the value of this argument ?

For example, I got a custom error:
error PaymentFailure(address to, uint256 value);

And I would like to check that this error is raised, but without knowing the value.

If so, would it be possible to update the ReadMe accordingly ?
Thank you.

**Comment by TomiOhl** [comment]
Hey, the last, `values` argument of expectRevertCustomError is optional - if you don't provide an array of expected values, they won't be validated and the test will only check the error name.
Added a comment to the readme based on your suggestion. Thanks!
